
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lending_edge
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
